[build]
  command = "npm run generate"
  publish = "dist"
  functions = "dist/functions"

[[redirects]]
  from = "/fetch"
  to = "/.netlify/functions/fetch"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
